### ISSUE TITLE
Recent update broke tutorials in forms

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/TutorialManager#16]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Form elements, despite seemingly receiving a z-index don't appear above the `driver.js` highlight anymore.
This worked just fine ~ 1 month ago

### Steps to Reproduce
1. Create a form
2. Add a tutorial to one of it's fields or buttons (example selectors that should work on any form: `form .columns .column:last-of-type .field` `form .button.is-primary`)
3. trigger the tutorial, note that the white background covers up what it's trying to highlight.

### Expected behavior

Highlighted element to remain visible

### Actual behavior

Highlighted element disappearing (seemingly as if z-index isn't getting applied for some reason)

**Comment by aocneanu** [comment]
I was able to reproduce but I really don't know what has changed in the last month (I never tested it with forms).

You don't have to set any z-index, driver.js is doing that for you. What you can do temporarily is remove the overlay from driver.js. We'll leave this open.

**Comment by jlsjonas** [comment]
![image](https://user-images.githubusercontent.com/932193/54931591-93906000-4f19-11e9-9d35-398d1eccbb21.png)
Seems broken (almost?) everywhere now, at least everywhere we use it.
